"use client";

import { useEffect, useMemo, useRef, useState } from "react";

const API = "http://127.0.0.1:8000";
type Row = Record<string, string | number | boolean | null>;
type DataPayload = { source:string; summary:any; preview:Row[]; benchmark:Row[]; process_features:Row[] };

function Sparkline({ rows, x, y, color="#26d7a0" }:{rows:Row[];x:string;y:string;color?:string}) {
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const c=ref.current;if(!c||!rows.length)return;const ctx=c.getContext("2d");if(!ctx)return;
    const dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);
    const valid=(value:any)=>value!==null&&value!==undefined&&value!==""&&Number.isFinite(Number(value));
    const vals=rows.map(r=>r[y]).filter(valid).map(Number);if(!vals.length)return;
    const lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1,left=54,right=14,top=16,bottom=31,pw=w-left-right,ph=h-top-bottom;
    ctx.strokeStyle="rgba(140,163,155,.18)";ctx.lineWidth=1;ctx.fillStyle="rgba(220,240,233,.76)";ctx.font="10px Segoe UI";
    for(let g=0;g<5;g++){const gy=top+g*ph/4,val=hi-g*span/4;ctx.beginPath();ctx.moveTo(left,gy);ctx.lineTo(w-right,gy);ctx.stroke();ctx.fillText(val.toFixed(2),4,gy+3)}
    const tickPositions=[0,Math.floor((rows.length-1)/2),rows.length-1];
    tickPositions.forEach((idx,t)=>{const raw=String(rows[idx]?.[x]||"");const date=new Date(raw);const label=Number.isNaN(date.getTime())?raw.slice(0,16):date.toLocaleString([], {month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"});const px=left+t*pw/2;ctx.textAlign=t===0?"left":t===2?"right":"center";ctx.fillText(label,px,h-8)});ctx.textAlign="left";
    ctx.strokeStyle="rgba(220,240,233,.35)";ctx.beginPath();ctx.moveTo(left,top);ctx.lineTo(left,h-bottom);ctx.lineTo(w-right,h-bottom);ctx.stroke();
    ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=5;ctx.lineWidth=2.2;ctx.beginPath();
    let drawing=false;rows.forEach((r,i)=>{if(!valid(r[y])){drawing=false;return}const v=Number(r[y]),px=left+i/(rows.length-1||1)*pw,py=top+(hi-v)/span*ph;drawing?ctx.lineTo(px,py):(ctx.moveTo(px,py),drawing=true)});ctx.stroke();ctx.shadowBlur=0;
  },[rows,x,y,color]);
  return <canvas ref={ref} className="chartCanvas" aria-label={`${y} time-series chart`}/>;
}

function ScatterPlot({rows,x,y}:{rows:Row[];x:string;y:string}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const valid=(v:any)=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));const pairs=rows.filter(r=>valid(r[x])&&valid(r[y])).map(r=>[Number(r[x]),Number(r[y])]);const dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);if(!pairs.length)return;
    const xs=pairs.map(p=>p[0]),ys=pairs.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),xspan=xmax-xmin||1,yspan=ymax-ymin||1,L=58,R=15,T=15,B=38,pw=w-L-R,ph=h-T-B;
    ctx.font="10px Segoe UI";ctx.fillStyle="rgba(220,240,233,.76)";ctx.strokeStyle="rgba(140,163,155,.18)";ctx.lineWidth=1;
    for(let i=0;i<5;i++){const px=L+i*pw/4,py=T+i*ph/4;ctx.beginPath();ctx.moveTo(px,T);ctx.lineTo(px,h-B);ctx.stroke();ctx.beginPath();ctx.moveTo(L,py);ctx.lineTo(w-R,py);ctx.stroke();ctx.textAlign="center";ctx.fillText((xmin+i*xspan/4).toFixed(2),px,h-19);ctx.textAlign="right";ctx.fillText((ymax-i*yspan/4).toFixed(2),L-6,py+3)}
    ctx.fillStyle="rgba(77,147,255,.38)";for(const [vx,vy] of pairs){const px=L+(vx-xmin)/xspan*pw,py=T+(ymax-vy)/yspan*ph;ctx.beginPath();ctx.arc(px,py,2.2,0,Math.PI*2);ctx.fill()}
    ctx.fillStyle="rgba(220,240,233,.8)";ctx.textAlign="center";ctx.fillText(x,L+pw/2,h-4);ctx.save();ctx.translate(12,T+ph/2);ctx.rotate(-Math.PI/2);ctx.fillText(y,0,0);ctx.restore();ctx.textAlign="left";
  },[rows,x,y]);return <canvas ref={ref} className="scatterCanvas" aria-label={`${x} versus ${y} scatter plot`}/>}

function EventTimeline({event}:{event:any}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const c=ref.current;if(!c||!event?.series?.length)return;const ctx=c.getContext("2d");if(!ctx)return;const rows=event.series,dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const L=72,R=16,T=18,B=32,gap=16,laneH=(h-T-B-gap*2)/3,pw=w-L-R;const times=rows.map((r:any)=>new Date(r.timestamp).getTime()),t0=Math.min(...times),t1=Math.max(...times),span=t1-t0||1,px=(t:number)=>L+(t-t0)/span*pw;
    const start=new Date(event.start_timestamp).getTime(),end=new Date(event.end_timestamp).getTime();ctx.fillStyle="rgba(238,168,59,.12)";ctx.fillRect(px(start),T,Math.max(3,px(end)-px(start)),h-T-B);ctx.strokeStyle="rgba(238,168,59,.65)";ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(px(start),T);ctx.lineTo(px(start),h-B);ctx.moveTo(px(end),T);ctx.lineTo(px(end),h-B);ctx.stroke();ctx.setLineDash([]);
    const lane=(index:number,label:string)=>{const y=T+index*(laneH+gap);ctx.fillStyle="rgba(220,240,233,.7)";ctx.font="10px Segoe UI";ctx.fillText(label,5,y+12);ctx.strokeStyle="rgba(140,163,155,.18)";ctx.strokeRect(L,y,pw,laneH);return y};
    const draw=(key:string,color:string,laneIndex:number,width=1.8)=>{const valid=(v:any)=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));const vals=rows.map((r:any)=>r[key]).filter(valid).map(Number);if(!vals.length)return;const lo=Math.min(...vals),hi=Math.max(...vals),range=hi-lo||1,y0=T+laneIndex*(laneH+gap);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();let drawing=false;rows.forEach((r:any)=>{if(!valid(r[key])){drawing=false;return}const v=Number(r[key]),x=px(new Date(r.timestamp).getTime()),y=y0+laneH-6-(v-lo)/range*(laneH-12);drawing?ctx.lineTo(x,y):(ctx.moveTo(x,y),drawing=true)});ctx.stroke()};
    lane(0,"Change score");lane(1,"Target + drivers");lane(2,"Prediction error");draw("process_change_score","#22d39b",0,2.2);if(rows[0].SLURRY_FREE_ACID!=null)draw("SLURRY_FREE_ACID","#ffffff",1,2.4);const colors=["#4d93ff","#c77dff","#ff6b8a"];event.driver_list?.forEach((d:string,i:number)=>draw(d,colors[i%3],1,1.5));draw("prediction_error","#eea83b",2,2.1);
    ctx.font="10px Segoe UI";ctx.fillStyle="rgba(220,240,233,.72)";ctx.textAlign="left";ctx.fillText(new Date(t0).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),L,h-9);ctx.textAlign="center";ctx.fillText("highlight = detected consecutive window",L+pw/2,h-9);ctx.textAlign="right";ctx.fillText(new Date(t1).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),w-R,h-9);ctx.textAlign="left";
  },[event]);return <canvas ref={ref} className="eventCanvas" aria-label="Transition event timeline"/>}

const Icon=({children}:{children:string})=><span className="icon">{children}</span>;

export default function Home(){
  const [data,setData]=useState<DataPayload|null>(null),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
  const [tab,setTab]=useState("Overview"),[variable,setVariable]=useState("SLURRY_FREE_ACID"),[mode,setMode]=useState("virtual_sensor"),[horizon,setHorizon]=useState(10);
  const [prediction,setPrediction]=useState<any>(null),[dark,setDark]=useState(true);
  const loadDefault=async()=>{setBusy(true);setError("");try{const r=await fetch(`${API}/api/default`);if(!r.ok)throw new Error("Local analytics service is not running.");setData(await r.json());setFile(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{loadDefault()},[]);
  const analyze=async(f:File)=>{setBusy(true);setError("");setFile(f);const body=new FormData();body.append("file",f);try{const r=await fetch(`${API}/api/analyze`,{method:"POST",body});if(!r.ok)throw new Error((await r.json()).detail);setData(await r.json());setPrediction(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const predict=async()=>{setBusy(true);setError("");try{let f=file;if(!f){const blob=await fetch("/default-data.csv").then(r=>r.blob());f=new File([blob],"tsp_1min.csv",{type:"text/csv"})}const body=new FormData();body.append("file",f);const r=await fetch(`${API}/api/predict/${mode}?horizon=${horizon}`,{method:"POST",body});if(!r.ok)throw new Error((await r.json()).detail);setPrediction(await r.json());setTab("Predictions")}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const nums=data?.summary.numeric_columns||[];useEffect(()=>{if(data&&!nums.includes(variable))setVariable(nums.includes("SLURRY_FREE_ACID")?"SLURRY_FREE_ACID":nums[0])},[data]);
  const chartRows=useMemo(()=>prediction?.preview||data?.preview||[],[prediction,data]);
  const predictionY=prediction?.preview?.[0]?("predicted_slurry_free_acid" in prediction.preview[0]?"predicted_slurry_free_acid":Object.keys(prediction.preview[0]).find(k=>k.startsWith("predicted_")&&k!=="predicted_change")):null;
  const report=()=>{if(!data)return;const s=data.summary;const observations=(s.observations||[]).map((x:string)=>`<li>${x}</li>`).join("");const windows=(s.change_windows||[]).slice(0,10).map((r:any)=>`<tr><td>${r.start_timestamp}</td><td>${r.end_timestamp}</td><td>${r.duration_minutes} min</td><td>${r.peak_process_change_score.toFixed(3)}</td><td>${r.drivers}</td><td>${r.target_response_10min?.toFixed(3)??"—"}</td><td>${r.error_change_pct?.toFixed(1)??"—"}%</td></tr>`).join("");const html=`<html><head><title>TSP Process Report</title><style>body{font:14px Arial;margin:40px;color:#17231f}h1{color:#087f5b}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:8px;text-align:left}small{color:#667}</style></head><body><h1>TSP Process Intelligence Report</h1><p>Source: ${data.source}</p><h2>Dataset summary</h2><p>${s.rows.toLocaleString()} rows · ${s.columns} columns · ${s.start} to ${s.end}</p><p>Target available: ${s.target_present?"Yes":"No"}; missing cells: ${s.missing_cells}; candidate transition rows: ${s.candidate_transition_rows}</p><h2>Automatic observations</h2><ul>${observations}</ul><h2>Candidate transition episodes</h2><table><thead><tr><th>Start</th><th>End</th><th>Duration</th><th>Peak score</th><th>Main drivers</th><th>Target Δ +10m</th><th>Error change</th></tr></thead><tbody>${windows}</tbody></table><small>Candidate windows are analytical labels, not confirmed plant events.</small><h2>Model mode</h2><p>${mode==="virtual_sensor"?"Target-free virtual sensor":"Target-anchored early warning"}</p><h2>Prediction result</h2><pre>${JSON.stringify(prediction?.metrics||"Not generated",null,2)}</pre><h2>Validation statement</h2><p>Predictions are associations, not causal recommendations. Drift flags indicate inputs outside the training envelope.</p><script>window.print()</script></body></html>`;const w=window.open();w?.document.write(html);w?.document.close()};
  const tabs=["Overview","Explore","Predictions","Model lab","Process map"];
  return <main className={dark?"app dark":"app"}>
    <aside className="sidebar"><div className="brand"><div className="brandMark">T</div><div><strong>TSP</strong><small>Process Intelligence</small></div></div>
      <nav>{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}><Icon>{({Overview:"⌂",Explore:"⌁",Predictions:"↗","Model lab":"◈","Process map":"⌘"} as any)[t]}</Icon>{t}</button>)}</nav>
      <div className="sideStatus"><span className="pulse"/><div><b>Models ready</b><small>Validated artifacts loaded</small></div></div>
      <button className="sideLink" onClick={report}>⇩ Generate report</button>
    </aside>
    <section className="workspace">
      <header><div><p className="eyebrow">OCP · TSP production line</p><h1>{tab}</h1></div><div className="headerActions"><button className="ghost" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><label className="upload">＋ Upload CSV<input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&analyze(e.target.files[0])}/></label></div></header>
      {error&&<div className="error"><b>Connection or data issue</b><span>{error}</span><button onClick={loadDefault}>Retry default data</button></div>}
      {busy&&<div className="loading"><span/><p>Preparing process intelligence…</p></div>}
      {!busy&&data&&<>
        <div className="datasetBar"><div><span className="liveDot"/><b>{data.source}</b><small>{data.summary.rows.toLocaleString()} observations</small></div><div className="datasetMeta"><span>{data.summary.start.slice(0,10)} → {data.summary.end.slice(0,10)}</span><span className={data.summary.target_present?"tag green":"tag amber"}>{data.summary.target_present?"Target available":"Process-only data"}</span></div></div>
        {tab==="Overview"&&<Overview data={data} rows={chartRows} variable={variable} setVariable={setVariable} predict={predict}/>} 
        {tab==="Explore"&&<Explore data={data} variable={variable} setVariable={setVariable} prediction={prediction}/>} 
        {tab==="Predictions"&&<Predictions data={data} prediction={prediction} rows={chartRows} y={predictionY} mode={mode} setMode={setMode} horizon={horizon} setHorizon={setHorizon} predict={predict}/>} 
        {tab==="Model lab"&&<ModelLab rows={data.benchmark}/>} 
        {tab==="Process map"&&<ProcessMap rows={data.process_features}/>} 
      </>}
    </section>
  </main>
}

function Overview({data,rows,variable,setVariable,predict}:any){const s=data.summary;return <div className="content">
  <div className="kpis"><Kpi label="Observations" value={s.rows.toLocaleString()} sub="one-minute records"/><Kpi label="Process variables" value={s.numeric_columns.length} sub={`${s.missing_cells.toLocaleString()} missing cells`}/><Kpi label="Target coverage" value={s.target_present?"Available":"Not provided"} sub={s.target_present?"evaluation enabled":"virtual-sensor mode"}/><Kpi label="Time span" value={`${Math.max(1,Math.round(s.rows/1440))} days`} sub="chronological data"/></div>
  <div className="grid twoOne"><section className="panel heroChart"><PanelHead title="Process trajectory" subtitle="Zoom-free overview of the selected signal"><select value={variable} onChange={e=>setVariable(e.target.value)}>{s.numeric_columns.map((v:string)=><option key={v}>{v}</option>)}</select></PanelHead><Sparkline rows={rows} x="Date" y={variable}/><div className="chartFooter"><span>Earlier</span><span>Later</span></div></section>
  <section className="panel actionPanel"><p className="eyebrow">Recommended action</p><h2>{s.target_present?"Forecast future movement":"Estimate free acidity"}</h2><p>{s.target_present?"Use the target-anchored model for 1–15 minute warning, or hide the target and test the virtual sensor.":"Run the validated process-only blend with uncertainty and drift monitoring."}</p><button className="primary" onClick={predict}>Generate predictions →</button><small>No model is refitted in the dashboard.</small></section></div>
  <div className="grid thirds"><section className="panel"><PanelHead title="Missingness watch" subtitle="Highest missing counts"/><MiniBars rows={s.missing_by_column} label="variable" value="missing"/></section><section className="panel"><PanelHead title="Target associations" subtitle={s.target_present?"Absolute correlation · descriptive only":"Available after labeled upload"}/>{s.correlations.length?<MiniBars rows={s.correlations} label="variable" value="absolute_correlation"/>:<Empty text="No target column in this dataset"/>}</section><section className="panel"><PanelHead title="Readiness" subtitle="Operational safeguards"/><ul className="checks"><li>✓ Target leakage blocked</li><li>✓ Chronological evaluation</li><li>✓ Cached preprocessing</li><li>✓ Drift flag included</li><li>△ Cross-month validation needed</li></ul></section></div>
  <section className="panel"><PanelHead title="Automatic observations" subtitle="Generated from this dataset, not fixed project text"/><div className="observationGrid">{s.observations.map((text:string,i:number)=><article key={i}><span>{String(i+1).padStart(2,"0")}</span><p>{text}</p></article>)}</div></section>
  </div>}

function Explore({data,variable,setVariable,prediction}:any){
  const [period,setPeriod]=useState("all");const s=data.summary;
  const [xVar,setXVar]=useState(s.numeric_columns[0]);const [yVar,setYVar]=useState(s.target_present?"SLURRY_FREE_ACID":s.numeric_columns[1]);
  const [selectedEvent,setSelectedEvent]=useState(0);const [eventLabels,setEventLabels]=useState<Record<number,string>>({});
  useEffect(()=>{if(!s.numeric_columns.includes(xVar))setXVar(s.numeric_columns[0]);if(!s.numeric_columns.includes(yVar))setYVar(s.target_present?"SLURRY_FREE_ACID":s.numeric_columns[1])},[data]);
  useEffect(()=>{setSelectedEvent(0);try{setEventLabels(JSON.parse(localStorage.getItem(`tsp-event-labels:${data.source}`)||"{}"))}catch{setEventLabels({})}},[data]);
  const filtered=useMemo(()=>{if(period==="all")return data.preview;const end=new Date(data.preview[data.preview.length-1]?.Date).getTime();const hours=Number(period);return data.preview.filter((r:Row)=>new Date(String(r.Date)).getTime()>=end-hours*3600000)},[data,period]);
  const relation=useMemo(()=>{const valid=(v:any)=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));const pairs=filtered.filter((r:Row)=>valid(r[xVar])&&valid(r[yVar])).map((r:Row)=>[Number(r[xVar]),Number(r[yVar])]);if(pairs.length<2)return {r:NaN,n:pairs.length};const mx=pairs.reduce((a:number,p:number[])=>a+p[0],0)/pairs.length,my=pairs.reduce((a:number,p:number[])=>a+p[1],0)/pairs.length;let cov=0,vx=0,vy=0;for(const p of pairs){cov+=(p[0]-mx)*(p[1]-my);vx+=(p[0]-mx)**2;vy+=(p[1]-my)**2}return {r:cov/Math.sqrt(vx*vy),n:pairs.length}},[filtered,xVar,yVar]);
  const relationText=!Number.isFinite(relation.r)?"Insufficient variation":Math.abs(relation.r)>=.7?"Strong":Math.abs(relation.r)>=.4?"Moderate":Math.abs(relation.r)>=.2?"Weak":"Very weak";
  const event=useMemo(()=>{const base=s.change_windows[selectedEvent];if(!base)return null;const error=prediction?.event_error_metrics?.find((e:any)=>e.event_id===base.event_id);if(!error)return base;const lookup=new Map((error.error_series||[]).map((r:any)=>[new Date(r.timestamp).getTime(),r.prediction_error]));return {...base,...error,series:base.series.map((r:any)=>({...r,prediction_error:lookup.get(new Date(r.timestamp).getTime())??null}))}},[s.change_windows,selectedEvent,prediction]);
  return <div className="content">
    <div className="toolbar"><div className="controlGroup"><label>Signal<select value={variable} onChange={e=>setVariable(e.target.value)}>{s.numeric_columns.map((v:string)=><option key={v}>{v}</option>)}</select></label><label>Time window<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Full dataset</option><option value="168">Last 7 days</option><option value="72">Last 3 days</option><option value="24">Last 24 hours</option><option value="6">Last 6 hours</option></select></label></div><span className="tag">{filtered.length.toLocaleString()} plotted samples</span></div>
    <section className="panel tall"><PanelHead title={variable} subtitle={`Y-axis: observed value · X-axis: timestamp · ${period==="all"?"full chronological range":`last ${period} hours`}`}/><Sparkline rows={filtered} x="Date" y={variable} color="#56a7ff"/></section>
    <div className="kpis"><Kpi label="Stable rows" value={s.stable_rows.toLocaleString()} sub="below process-change threshold"/><Kpi label="Candidate transitions" value={s.candidate_transition_rows.toLocaleString()} sub="top 5% multivariate changes"/><Kpi label="Transition share" value={(100*s.candidate_transition_rows/s.rows).toFixed(1)+"%"} sub="candidate label, not plant event"/><Kpi label="Sampling cadence" value={s.sampling_interval_minutes.toFixed(1)+" min"} sub="median timestamp interval"/></div>
    <div className="grid relationGrid"><section className="panel"><PanelHead title="Most dynamic process signals" subtitle="Typical movement normalized by each sensor's own IQR"/><MiniBars rows={s.sensor_dynamics} label="variable" value="median_normalized_step"/><p className="methodNote">This ranks movement, not predictive importance or causal influence.</p></section><section className="panel"><PanelHead title="Relationship explorer" subtitle="Compare any two observed variables in the selected time window"/><div className="pairControls"><label>X variable<select value={xVar} onChange={e=>setXVar(e.target.value)}>{s.numeric_columns.map((v:string)=><option key={v}>{v}</option>)}</select></label><button onClick={()=>{setXVar(yVar);setYVar(xVar)}}>⇄</button><label>Y variable<select value={yVar} onChange={e=>setYVar(e.target.value)}>{s.numeric_columns.map((v:string)=><option key={v}>{v}</option>)}</select></label></div><div className="relationshipStats"><span>Pearson correlation <b>{Number.isFinite(relation.r)?relation.r.toFixed(3):"—"}</b></span><span>Pattern <b>{relationText} {Number.isFinite(relation.r)?relation.r>=0?"positive":"negative":""}</b></span><span>Valid pairs <b>{relation.n.toLocaleString()}</b></span></div><ScatterPlot rows={filtered} x={xVar} y={yVar}/><p className="methodNote">Correlation describes association in this selected window. Nonlinear structure, common causes and time delays can exist even when Pearson correlation is small.</p></section></div>
    <section className="panel eventInvestigator"><PanelHead title="Transition-window investigator" subtitle="Select a detected episode to inspect its duration, drivers, target response and model error"/>
      <div className="eventStrip">{s.change_windows.map((r:any,i:number)=><button key={r.event_id} className={selectedEvent===i?"active":""} onClick={()=>setSelectedEvent(i)}><span>Window {String(r.event_id).padStart(2,"0")}</span><b>{new Date(r.start_timestamp).toLocaleString([], {month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</b><small>{r.duration_minutes} min · peak {r.peak_process_change_score.toFixed(3)}</small></button>)}</div>
      {event&&<><div className="eventSummary"><article><span>Consecutive duration</span><b>{event.duration_minutes} minute{event.duration_minutes===1?"":"s"}</b><small>{new Date(event.start_timestamp).toLocaleTimeString()} → {new Date(event.end_timestamp).toLocaleTimeString()}</small></article><article><span>Main sensor drivers</span><b>{event.driver_list[0]}</b><small>{event.driver_list.slice(1).join(" · ")}</small></article><article><span>Cumulative target change by +10 min</span><b className={Math.abs(event.target_response_10min||0)>.2?"attention":""}>{event.target_response_10min==null?"Unavailable":`${event.target_response_10min>=0?"+":""}${event.target_response_10min.toFixed(3)}`}</b><small>{event.target_before_window?.toFixed(3)??"—"} before → {event.target_after_10min?.toFixed(3)??"—"} ten min after end · {event.target_after_10min_empirical_status}</small></article><article><span>Prediction-error change</span><b className={(event.error_change_pct||0)>20?"attention":""}>{event.error_change_pct==null?"Run a prediction":`${event.error_change_pct>=0?"+":""}${event.error_change_pct.toFixed(1)}%`}</b><small>{event.error_change_pct==null?"then return here to compare error":"30 min before vs window + 30 min after"}</small></article></div>
      <div className="eventLegend"><span className="changeLine">Multivariate process-change score</span><span className="targetLine">SLURRY_FREE_ACID</span>{event.driver_list.map((d:string,i:number)=><span className={`driverLine d${i}`} key={d}>{d}</span>)}<span className="errorLine">Prediction absolute error</span></div><EventTimeline event={event}/>
      <div className="eventBottom"><div className="responseCards"><div><span>Change during window</span><b>{event.target_change_during_window==null?"—":`${event.target_change_during_window>=0?"+":""}${event.target_change_during_window.toFixed(3)}`}</b></div>{[5,10,15].map(lag=><div key={lag}><span>Additional change after end +{lag} min</span><b>{event[`target_delayed_response_${lag}min`]==null?"—":`${event[`target_delayed_response_${lag}min`]>=0?"+":""}${event[`target_delayed_response_${lag}min`].toFixed(3)}`}</b></div>)}</div><label className="eventLabel">Known plant event or operator note<input value={eventLabels[event.event_id]||""} placeholder="Example: grade change, startup, maintenance…" onChange={e=>{const next={...eventLabels,[event.event_id]:e.target.value};setEventLabels(next);localStorage.setItem(`tsp-event-labels:${data.source}`,JSON.stringify(next))}}/><small>{eventLabels[event.event_id]?"Saved locally as user-supplied plant context.":"Unlabeled until confirmed against plant logs."}</small></label></div></>}
      <p className="methodNote">Orange shading marks consecutive process-change rows. The white target and driver lines are independently rescaled within this local window, so use them to compare timing and shape—not absolute magnitude. “Cumulative” compares immediately before the window with ten minutes after it ends; “additional change” isolates movement after the window end. Neither establishes causality.</p>
    </section>
    <section className="panel compactGuide"><PanelHead title="Interpretation workflow" subtitle="Use the change-window table and relationship explorer together"/><ol className="guide inlineGuide"><li>Choose a driver from a detected window.</li><li>Compare it with the target or another process signal.</li><li>Change the time window to test whether the relationship is stable.</li></ol></section>
  </div>}

function Predictions({data,prediction,rows,y,mode,setMode,horizon,setHorizon,predict}:any){return <div className="content"><div className="modeGrid"><button className={mode==="virtual_sensor"?"mode active":"mode"} onClick={()=>setMode("virtual_sensor")}><b>Target-free virtual sensor</b><span>Process variables only</span><small>Use when no acidity values exist</small></button><button disabled={!data.summary.target_present} className={mode==="early_warning"?"mode active":"mode"} onClick={()=>setMode("early_warning")}><b>Target-anchored warning</b><span>Current target + process history</span><small>{data.summary.target_present?"Forecast 1–15 minutes ahead":"Requires SLURRY_FREE_ACID"}</small></button></div><div className="runbar">{mode==="early_warning"&&<label>Horizon <select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}>{[1,5,10,15].map(x=><option key={x} value={x}>{x} minutes</option>)}</select></label>}<button className="primary" onClick={predict}>Run validated pipeline</button>{prediction&&<a className="download" href={`${API}/api/download/${prediction.result_id}`}>Download full predictions</a>}</div>{prediction?<><div className="kpis"><Kpi label="Predicted rows" value={prediction.rows.toLocaleString()} sub="after warm-up"/><Kpi label="MAE" value={prediction.metrics?.mae!=null?prediction.metrics.mae.toFixed(3):"—"} sub={prediction.metrics?`${prediction.metrics.evaluated_rows||prediction.rows} labeled rows`:"labels unavailable"}/><Kpi label="RMSE" value={prediction.metrics?.rmse!=null?prediction.metrics.rmse.toFixed(3):"—"} sub="future observed versus predicted"/><Kpi label="90% coverage" value={prediction.metrics?.coverage_90!=null?(prediction.metrics.coverage_90*100).toFixed(1)+"%":"N/A"} sub={mode==="early_warning"?"interval not calibrated for this model":"empirical interval"}/></div><section className="panel tall"><PanelHead title="Prediction trajectory" subtitle="Point estimate with downloadable row-level output"/>{y&&<Sparkline rows={rows} x="Date" y={y}/>}</section></>:<Empty text="Choose a mode and run the validated pipeline"/>}</div>}

function ModelLab({rows}:any){return <div className="content"><section className="panel"><PanelHead title="Target-free benchmark" subtitle="Models selected on chronological validation; test shown once"/><div className="tableWrap"><table><thead><tr><th>Feature set</th><th>Model</th><th>Validation RMSE</th><th>Test RMSE</th><th>Test R²</th></tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i}><td>{r.feature_set}</td><td><b>{r.model}</b></td><td>{Number(r.valid_rmse).toFixed(3)}</td><td>{Number(r.test_rmse).toFixed(3)}</td><td>{Number(r.test_r2).toFixed(3)}</td></tr>)}</tbody></table></div></section><div className="callout"><b>Current research winner</b><span>50/50 Ridge + LightGBM blend · RMSE 0.301 · R² 0.558</span><p>Strong within-month evidence, but a genuinely separate labeled month is still required to claim monthly generalization.</p></div></div>}

function ProcessMap({rows}:any){return <div className="content"><div className="callout"><b>Interpretability boundary</b><span>Predictive association is not causality.</span><p>No dashboard suggestion authorizes changing an input unless the process registry confirms it is controllable.</p></div><div className="processGrid">{rows.map((r:any,i:number)=><article className="panel process" key={i}><span className={`status ${String(r.validation_status).includes("confirmed")?"ok":"warn"}`}>{r.validation_status}</span><h3>{r.feature}</h3><code>{r.formula}</code><p>{r.expected_interpretation}</p><small>{r.assumptions}</small></article>)}</div></div>}

function Kpi({label,value,sub}:{label:string,value:string,sub:string}){return <article className="kpi"><span>{label}</span><b>{value}</b><small>{sub}</small></article>}
function PanelHead({title,subtitle,children}:{title:string,subtitle:string,children?:React.ReactNode}){return <div className="panelHead"><div><h3>{title}</h3><p>{subtitle}</p></div>{children}</div>}
function MiniBars({rows,label,value}:any){const max=Math.max(...rows.map((r:any)=>Number(r[value])),1);return <div className="miniBars">{rows.slice(0,7).map((r:any,i:number)=><div key={i}><span title={r[label]}>{r[label]}</span><i><em style={{width:`${Number(r[value])/max*100}%`}}/></i><b>{Number(r[value]).toFixed(Number(r[value])<1?2:0)}</b></div>)}</div>}
function Empty({text}:{text:string}){return <div className="empty"><span>◇</span><p>{text}</p></div>}
